settings:
  title: "Animo's Websites Status Page"
  url: 'https://status.animo.top/' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: www-animo-top # unique identifier
    name: www.animo.top
    description: '' # default=empty
    url: 'https://www.animo.top/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true
    
  - id: blog-animo-top
    name: blog.animo.top
    url: 'https://blog.animo.top/'
    method: GET
    expectStatus: 200
    linkable: true

  - id: img-animo-top
    name: Animo's Image Hosting Service
    url: 'https://i.animo.top/'
    method: GET
    expectStatus: 200
    linkable: true

  - id: api-animo-top
    name: api.animo.top
    description: ''
    url: 'https://api.animo.top/dingtalk/'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

#   - id: blog-cloudflare-com
#     name: The Cloudflare Blog
#     url: 'https://blog.cloudflare.com/'
#     method: GET
#     expectStatus: 200
